steps:
  # 1. Construction de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_REGION-docker.pkg.dev/taskflow-api-486912/$_REPO_NAME/taskflow-api:$SHORT_SHA',
        '.',
      ]

  # 2. Envoi de l'image vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/taskflow-api:$SHORT_SHA',
      ]

  # 3. Déploiement sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taskflow-api-service' # Nom de votre service Cloud Run
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/taskflow-api:$SHORT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Pour que l'API soit publique

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/taskflow-api:$SHORT_SHA'

substitutions:
  _REGION: 'europe-west1' # À modifier selon ta région
  _REPO_NAME: 'taskflow-api' # À modifier selon ton dépôt Artifact Registry

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
